"""DEAPack: DEA-based efficiency and productivity analysis."""

from importlib.metadata import PackageNotFoundError, version

from .analysis import (
    APZMalmquistLuenbergerDEA,
    APZMalmquistLuenbergerProductivityIndex,
    BiennialMalmquistDEA,
    BiennialMalmquistProductivityIndex,
    FGNZEnhancedMalmquist,
    FGNZEnhancedMalmquistProductivityIndex,
    FGNZMalmquist,
    FGNZMalmquistProductivityIndex,
    GlobalMalmquistDEA,
    GlobalMalmquistLuenbergerDEA,
    GlobalMalmquistLuenbergerProductivityIndex,
    GlobalMalmquistProductivityIndex,
    HicksMoorsteenDEA,
    HicksMoorsteenProductivityIndex,
    LuenbergerDEA,
    LuenbergerProductivityIndicator,
    MalmquistDEA,
    MalmquistLuenbergerDEA,
    MalmquistLuenbergerProductivityIndex,
    MalmquistProductivityIndex,
    MetafrontierDEA,
    MoorsteenBjurekDEA,
    MoorsteenBjurekProductivityIndex,
    RadialMetafrontierDEA,
    RayDesliMalmquist,
    RayDesliMalmquistProductivityIndex,
    ReferenceFrequencyResult,
    local_returns_to_scale,
    reference_frequency,
    relative_directional_scale_elasticity,
    scale_efficiency,
    scale_elasticity,
)
from .catalog import MethodInfo, list_methods, method_info
from .data import DEAData
from .datasets import (
    DatasetInfo,
    DatasetProvenance,
    DatasetVariableInfo,
    dataset_info,
    list_datasets,
    load_dataset,
    retired_dataset_migrations,
)
from .dynamic import (
    CarryOverKind,
    CarryOverSpec,
    DynamicData,
    DynamicSBM,
    DynamicSBMSpec,
    DynamicSpec,
    PeriodProductionSpec,
    ToneTsutsuiDynamicSBM,
)
from .dynamic_network import (
    DynamicNetworkData,
    DynamicNetworkSBM,
    DynamicNetworkSBMSpec,
    NetworkSBMLinkKind,
    ProcessCarryOverSpec,
    ToneTsutsuiDynamicNetworkSBM,
)
from .economics import (
    AllocativeDecomposition,
    CostEfficiency,
    GDFProfitabilityDecomposition,
    NerlovianEfficiency,
    NerlovianProfitInefficiency,
    PriceData,
    PriceSpec,
    ProfitabilityDecomposition,
    ProfitabilityEfficiency,
    ProfitEfficiency,
    ResolvedPrices,
    ReturnToDollarEfficiency,
    RevenueAllocativeDecomposition,
    RevenueEfficiency,
)
from .enums import (
    BadOutputDisposability,
    MultiplicativeVariant,
    Orientation,
    ReferenceKind,
    ReturnsToScale,
    SolverStatus,
)
from .evaluation import (
    GameCrossEfficiency,
    LiangWuCookZhuGameCrossEfficiency,
    NerloveLuenbergerSuperEfficiency,
    RayDirectionalSuperEfficiency,
    SuperSBM,
    ToneSuperSBM,
)
from .exceptions import (
    DataValidationError,
    DEAPackError,
    ModelSpecificationError,
    SolverError,
)
from .models.additive import RAM, AdditiveDEA, RangeAdjustedDEA, WeightedAdditiveDEA
from .models.bam import BAM, BoundedAdjustedDEA
from .models.by_production import (
    ByProductionDDF,
    ByProductionDirectionalDistanceDEA,
)
from .models.by_production_fgl import (
    ByProductionFareGrosskopfLovellDEA,
    ByProductionFGL,
)
from .models.directional import DDF, DirectionalDistanceDEA
from .models.ebm import DeclaredEBMCalibration, InputOrientedEpsilonBasedDEA
from .models.environmental import (
    ChungFareGrosskopfDDF,
    CommonFactorWeakDisposalDDF,
    EnvironmentalDDF,
    EnvironmentalDirectionalDistanceDEA,
)
from .models.fch import FCH, FreeCoordinationHullDEA
from .models.fdh import FDH, FreeDisposalHullDEA
from .models.frh import FRH, FreeReplicabilityHullDEA
from .models.generalized_distance import (
    GDF,
    ChavasCoxGDF,
    GeneralizedDistanceDEA,
)
from .models.material_balance import (
    CoelliMaterialBalanceDEA,
    MaterialBalanceCoefficients,
    MaterialBalanceDEA,
)
from .models.multiplicative import (
    C2S2MultiplicativeDEA,
    InvariantMultiplicativeDEA,
    MultiplicativeDEA,
)
from .models.nonseparable_sbm import (
    SBMNS,
    NonSeparableUndesirableSBM,
    ToneNonSeparableSBM,
)
from .models.radial import (
    BCC,
    CCR,
    BCCInput,
    BCCOutput,
    CCRInput,
    CCROutput,
    RadialDEA,
)
from .models.range_directional import RDM, RangeDirectionalDEA
from .models.sbm import (
    ERG,
    SBM,
    InputOrientedSlacksBasedDEA,
    InputRussell,
    InputSBM,
    OutputOrientedSlacksBasedDEA,
    OutputRussell,
    OutputSBM,
    SlacksBasedDEA,
    UndesirableSBM,
    UndesirableSlacksBasedDEA,
)
from .models.weak_disposal import (
    ActivitySpecificWeakDisposalDDF,
    KuosmanenWeakDisposalDDF,
)
from .models.zhou_ang_wang import (
    NonCHPEnergyCarbonDEA,
    ZhouAngWangNonCHPEnergyCarbonDEA,
)
from .network import (
    ChenCookLiZhuAdditiveDEA,
    CookZhuBiYangAdditiveDEA,
    EnvironmentalNetworkData,
    EnvironmentalNetworkSpec,
    EnvironmentalVariableOwnership,
    FareGrosskopfNetworkRadialDEA,
    GeneralAdditiveNetworkDEA,
    KalhorKazemiMatinNetworkDEA,
    KaoHwangDEA,
    KaoHwangRelationalDEA,
    LewisSextonSequentialNetworkDEA,
    LinkSpec,
    NetworkData,
    NetworkSBM,
    NetworkSpec,
    ProcessSpec,
    ToneTsutsuiNetworkSBM,
    TwoStageAdditiveDecompositionDEA,
    TwoStageSeriesSpec,
)
from .panel import (
    MultiperiodAggregativeDEA,
    ParkParkMultiperiodAggregativeDEA,
)
from .reporting import PublicationBundleNotAvailableError, publish_result
from .results import DEAResult
from .specs import ReferenceSpec, SolverOptions, TechnologySpec
from .technology import PeerEligibility, PeerEligibilityProvenance
from .valuation import (
    ConeRestrictionProvenance,
    PolyhedralConeRatioDEA,
    PolyhedralConeRatioResult,
)

__all__ = [
    "BAM",
    "BCC",
    "CCR",
    "DDF",
    "ERG",
    "FCH",
    "FDH",
    "FRH",
    "GDF",
    "RAM",
    "RDM",
    "SBM",
    "SBMNS",
    "APZMalmquistLuenbergerDEA",
    "APZMalmquistLuenbergerProductivityIndex",
    "ActivitySpecificWeakDisposalDDF",
    "AdditiveDEA",
    "AllocativeDecomposition",
    "BCCInput",
    "BCCOutput",
    "BadOutputDisposability",
    "BiennialMalmquistDEA",
    "BiennialMalmquistProductivityIndex",
    "BoundedAdjustedDEA",
    "ByProductionDDF",
    "ByProductionDirectionalDistanceDEA",
    "ByProductionFGL",
    "ByProductionFareGrosskopfLovellDEA",
    "C2S2MultiplicativeDEA",
    "CCRInput",
    "CCROutput",
    "CarryOverKind",
    "CarryOverSpec",
    "ChavasCoxGDF",
    "ChenCookLiZhuAdditiveDEA",
    "ChungFareGrosskopfDDF",
    "CoelliMaterialBalanceDEA",
    "CommonFactorWeakDisposalDDF",
    "ConeRestrictionProvenance",
    "CookZhuBiYangAdditiveDEA",
    "CostEfficiency",
    "DEAData",
    "DEAPackError",
    "DEAResult",
    "DataValidationError",
    "DatasetInfo",
    "DatasetProvenance",
    "DatasetVariableInfo",
    "DeclaredEBMCalibration",
    "DirectionalDistanceDEA",
    "DynamicData",
    "DynamicNetworkData",
    "DynamicNetworkSBM",
    "DynamicNetworkSBMSpec",
    "DynamicSBM",
    "DynamicSBMSpec",
    "DynamicSpec",
    "EnvironmentalDDF",
    "EnvironmentalDirectionalDistanceDEA",
    "EnvironmentalNetworkData",
    "EnvironmentalNetworkSpec",
    "EnvironmentalVariableOwnership",
    "FGNZEnhancedMalmquist",
    "FGNZEnhancedMalmquistProductivityIndex",
    "FGNZMalmquist",
    "FGNZMalmquistProductivityIndex",
    "FareGrosskopfNetworkRadialDEA",
    "FreeCoordinationHullDEA",
    "FreeDisposalHullDEA",
    "FreeReplicabilityHullDEA",
    "GDFProfitabilityDecomposition",
    "GameCrossEfficiency",
    "GeneralAdditiveNetworkDEA",
    "GeneralizedDistanceDEA",
    "GlobalMalmquistDEA",
    "GlobalMalmquistLuenbergerDEA",
    "GlobalMalmquistLuenbergerProductivityIndex",
    "GlobalMalmquistProductivityIndex",
    "HicksMoorsteenDEA",
    "HicksMoorsteenProductivityIndex",
    "InputOrientedEpsilonBasedDEA",
    "InputOrientedSlacksBasedDEA",
    "InputRussell",
    "InputSBM",
    "InvariantMultiplicativeDEA",
    "KalhorKazemiMatinNetworkDEA",
    "KaoHwangDEA",
    "KaoHwangRelationalDEA",
    "KuosmanenWeakDisposalDDF",
    "LewisSextonSequentialNetworkDEA",
    "LiangWuCookZhuGameCrossEfficiency",
    "LinkSpec",
    "LuenbergerDEA",
    "LuenbergerProductivityIndicator",
    "MalmquistDEA",
    "MalmquistLuenbergerDEA",
    "MalmquistLuenbergerProductivityIndex",
    "MalmquistProductivityIndex",
    "MaterialBalanceCoefficients",
    "MaterialBalanceDEA",
    "MetafrontierDEA",
    "MethodInfo",
    "ModelSpecificationError",
    "MoorsteenBjurekDEA",
    "MoorsteenBjurekProductivityIndex",
    "MultiperiodAggregativeDEA",
    "MultiplicativeDEA",
    "MultiplicativeVariant",
    "NerloveLuenbergerSuperEfficiency",
    "NerlovianEfficiency",
    "NerlovianProfitInefficiency",
    "NetworkData",
    "NetworkSBM",
    "NetworkSBMLinkKind",
    "NetworkSpec",
    "NonCHPEnergyCarbonDEA",
    "NonSeparableUndesirableSBM",
    "Orientation",
    "OutputOrientedSlacksBasedDEA",
    "OutputRussell",
    "OutputSBM",
    "ParkParkMultiperiodAggregativeDEA",
    "PeerEligibility",
    "PeerEligibilityProvenance",
    "PeriodProductionSpec",
    "PolyhedralConeRatioDEA",
    "PolyhedralConeRatioResult",
    "PriceData",
    "PriceSpec",
    "ProcessCarryOverSpec",
    "ProcessSpec",
    "ProfitEfficiency",
    "ProfitabilityDecomposition",
    "ProfitabilityEfficiency",
    "PublicationBundleNotAvailableError",
    "RadialDEA",
    "RadialMetafrontierDEA",
    "RangeAdjustedDEA",
    "RangeDirectionalDEA",
    "RayDesliMalmquist",
    "RayDesliMalmquistProductivityIndex",
    "RayDirectionalSuperEfficiency",
    "ReferenceFrequencyResult",
    "ReferenceKind",
    "ReferenceSpec",
    "ResolvedPrices",
    "ReturnToDollarEfficiency",
    "ReturnsToScale",
    "RevenueAllocativeDecomposition",
    "RevenueEfficiency",
    "SlacksBasedDEA",
    "SolverError",
    "SolverOptions",
    "SolverStatus",
    "SuperSBM",
    "TechnologySpec",
    "ToneNonSeparableSBM",
    "ToneSuperSBM",
    "ToneTsutsuiDynamicNetworkSBM",
    "ToneTsutsuiDynamicSBM",
    "ToneTsutsuiNetworkSBM",
    "TwoStageAdditiveDecompositionDEA",
    "TwoStageSeriesSpec",
    "UndesirableSBM",
    "UndesirableSlacksBasedDEA",
    "WeightedAdditiveDEA",
    "ZhouAngWangNonCHPEnergyCarbonDEA",
    "dataset_info",
    "list_datasets",
    "list_methods",
    "load_dataset",
    "local_returns_to_scale",
    "method_info",
    "publish_result",
    "reference_frequency",
    "relative_directional_scale_elasticity",
    "retired_dataset_migrations",
    "scale_efficiency",
    "scale_elasticity",
]

try:
    __version__ = version("DEAPack")
except PackageNotFoundError:
    __version__ = "0+unknown"
